### ISSUE TITLE
Live preview possible?

### ISSUE THREAD

**Issue by olach** [onecrayon/E3-Theme-Generator#1]
I've tried your suggestion to create a symlink for the generated css file into the Espresso Theme folder. This works, but I need to restart Espresso every time I make an edit to see the changes.

Is it possible to get the live preview to work somehow? When I edit a css theme file directly in the Espresso Theme folder, I get a live preview without even saving. But it doesn't seem to work when using this approach using symlinks and the Sass compilation step.

**Comment by onecrayon** [comment]
Sorry for the super late response to this! I completely lost track of it in my Sea of Tabs.

I'm not sure if it's possible to get live previewing for themes with a SASS-generated theme. I'm hoping to experiment at some point, but life is a little hectic at the moment so I can't make any promises.

**Comment by onecrayon** [comment]
Live preview via symlink now works perfectly as of [Espresso v4](http://espressoapp.com/updates/)!
